name: Run Weather Model

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"

permissions:
  contents: write

jobs:
  run_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas numpy requests pyarrow scikit-learn joblib

      - name: Run model pipeline
        run: |
          python code/05_build_observations_model_and_score.py

      - name: Commit parquet outputs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data/dashboard/observations_model.parquet
          git add data/dashboard/forecast_model.parquet

          git diff --cached --quiet || git commit -m "update model forecast"

          git pull --rebase
          git push
